services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cs2
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: 2g  

  web-django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: api_devtest
    command: sh -c "sleep 10 && poetry run python api_devtest/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - selenium
    env_file:
      - .env
    volumes:
      - ./api_devtest:/app/api_devtest
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock

  migration:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: api_devtest
    command: sh -c "sleep 10 && poetry run python api_devtest/manage.py migrate --noinput"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./api_devtest:/app/api_devtest
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock

volumes:
  db_data:
