FROM python:3.13-alpine

# Configuración máquina
RUN apk update && apk add --no-cache \
    build-base \
    libpq \
    pkgconfig \
    mysql-dev \
    mariadb-connector-c-dev \
    python3-dev \
    curl 

RUN pip install --upgrade pip poetry 

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

# Copiar todo el proyecto antes de instalar dependencias
WORKDIR /app
COPY pyproject.toml poetry.lock README.md /app/
COPY ./api_devtest /app/api_devtest

# Configuración Poetry para dependencias globales
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

EXPOSE 8000

CMD ["poetry", "run", "python", "api_devtest/manage.py", "runserver", "0.0.0.0:8000"]
