# Generated by Django 5.2.4 on 2025-08-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs2TeamsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Players',
                'db_table': 'player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Type Players',
                'db_table': 'type_player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('world_ranking', models.PositiveIntegerField()),
                ('valve_ranking', models.PositiveIntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='cs2TeamsApp.player')),
                ('players', models.ManyToManyField(related_name='players', to='cs2TeamsApp.player')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='type_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_player', to='cs2TeamsApp.type_player'),
        ),
    ]
